# permissions for end users to view appbundlebases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: appbundlebase-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: atrok
    app.kubernetes.io/part-of: atrok
    app.kubernetes.io/managed-by: kustomize
  name: appbundlebase-viewer-role
rules:
- apiGroups:
  - atro.xyz
  resources:
  - appbundlebases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - atro.xyz
  resources:
  - appbundlebases/status
  verbs:
  - get
