# permissions for end users to edit appbundles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: appbundle-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: atrok
    app.kubernetes.io/part-of: atrok
    app.kubernetes.io/managed-by: kustomize
  name: appbundle-editor-role
rules:
- apiGroups:
  - atro.xyz
  resources:
  - appbundles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - atro.xyz
  resources:
  - appbundles/status
  verbs:
  - get
