---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - atro.xyz
  resources:
  - appbundlebases
  - appbundles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - atro.xyz
  resources:
  - appbundlebases/finalizers
  - appbundles/finalizers
  verbs:
  - update
- apiGroups:
  - atro.xyz
  resources:
  - appbundlebases/status
  - appbundles/status
  verbs:
  - get
  - patch
  - update
