apiVersion: atro.xyz/v1alpha1
kind: AppBundle
metadata:
  labels:
    app.kubernetes.io/name: appbundle
  name: appbundle-sample
spec:
  image:
    repository: linuxserver/sonarr
    pullPolicy: Always
    tag: 4.0.0-develop
  resources:
    requests:
      cpu: 350m
      memory: 400Mi
    limits:
      cpu: 1000m
      memory: 1200Mi
  routes:
    - name: web
      port: 8989
      ingress:
        domain: test.sonarr.atro.xyz
        auth: true
  volumes:
    - name: sonarr-conf
      path: /config
      size: 8Gi
      storageClass: longhorn
      longhorn:
        backup:
          frequency: "0 0 * * *"
          retain: 5
