apiVersion: atro.xyz/v1alpha1
kind: AppBundle
metadata:
  name: atrok-test
spec:
  base: atrok-test-base
  image:
    repository: linuxserver/sonarr
    pullPolicy: Always
    tag: 4.0.0-develop
  routes:
    - name: web
      port: 8989
      ingress:
        domain: test.sonarr.atro.xyz
        auth: true
  volumes:
    - name: sonarr-conf
      path: /config
      size: 8Gi
      storageClass: longhorn
      longhorn:
        backup:
          frequency: "0 0 * * *"
          retain: 5
    - name: media
      path: /media
      existingClaim: media
  livenessProbe:
    failureThreshold: 5
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 10
    exec:
      command:
        - /usr/bin/env
        - bash
        - -c
        - curl --fail localhost:8989/api/v3/system/status?apiKey=`IFS=\> && while read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`