apiVersion: atro.xyz/v1alpha1
kind: AppBundle
metadata:
  labels:
    app.kubernetes.io/name: atrok
  name: atrok
spec:
  image:
    repository: harbor.atro.xyz/atrok/atrok
    pullPolicy: Always
    tag: latest
  resources:
    requests:
      cpu: 350m
      memory: 400Mi
    limits:
      cpu: 1000m
      memory: 1200Mi