name: Test
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v ./...
      - name: Setup envtest
        run: make envtest
      - name: Test
        run: make test
    # Will be helm install testing at some point, not yet. 
    # - name: Create k8s Kind Cluster
    #   uses: helm/kind-action@v1
    #   with:
    #     cluster_name: "operator-testing"
    #     kubectl_version: "v1.28.6"
