name: Test
on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true
  pull_request:
    branches: ["main"]
  push:
    branches:
      - "main"
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v ./...
      - name: Setup envtest
        run: make envtest
      - name: Test
        run: ATROK_TEST_ENV="integration" make test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: atropos112/atrok
  end2end-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v ./...
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: "operator-testing"
          kubectl_version: "v1.28.6"
      - name: Install CRDs
        run: make install
      - name: Test
        run: ATROK_TEST_ENV="end2end" make test
