name: Test
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v ./...
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          kubectl_version: "v1.28.6"
      - name: Setup Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo
      - name: Test with the Ginkgo CLI
        run: ginkgo run internal/controller
